# nixpacks.toml
[phases.setup]
# Installs required system libraries for OpenCV
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0"]

[start]
# Specifies the command to start your application
cmd = "python main.py"
